name: poky-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 01:42 UTC every Saturday
  schedule:
    - cron: '42 1 * * 6'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        base_distro: [
                      alma-8,
                      alma-9,
                      centos-7,
                      debian-9,
                      debian-10,
                      debian-11,
                      fedora-34,
                      fedora-35,
                      fedora-36,
                      opensuse-15.2,
                      opensuse-15.3,
                      opensuse-15.4,
                      ubuntu-18.04,
                      ubuntu-20.04,
                      ubuntu-22.04
        ]
    env:
      BASE_DISTRO: ${{ matrix.base_distro }}
      BASE_REPO: ${{ vars.base_repo }}
      REPO: ${{ vars.repo }}
      DEFAULT_DISTRO: ubuntu-18.04
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          push: false
          build-args: |
              BASE_REPO=${{ vars.base_repo }}
              BASE_DISTRO=${{ matrix.base_distro }}
          tags: |
            ${{ vars.REPO }}:${{ matrix.base_distro }}
            ghcr.io/${{ vars.REPO }}:${{ matrix.base_distro }}

      - name: Run tests
        run: |
          if command -v annotate-output; then
              ANNOTATE_OUTPUT=annotate-output
          fi
          $ANNOTATE_OUTPUT bash -c "cd tests; ./runtests.sh ${REPO}:${BASE_DISTRO}"

      - name: Push container image
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
              BASE_REPO=${{ vars.base_repo }}
              BASE_DISTRO=${{ matrix.base_distro }}
          tags: |
            ${{ vars.REPO }}:${{ matrix.base_distro }}
            ghcr.io/${{ vars.REPO }}:${{ matrix.base_distro }}

